In [16]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
#importing dataset using pandas
df = pd.read_csv(r'C:\Users\KIIT\Desktop\Internity Internship\Day 4 task\train.csv')
df.shape
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [18]:
#Taking a look at the data format below
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [19]:
#Taking a look at all the columns in the data set
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [20]:
#independet data 
X = df.iloc[:, 1:-1].values
#dependent data 
y = df.iloc[:, -1].values

In [21]:
print(X)

[[0 3 'Braund, Mr. Owen Harris' ... 'A/5 21171' 7.25 nan]
 [1 1 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)' ...
  'PC 17599' 71.2833 'C85']
 [1 3 'Heikkinen, Miss. Laina' ... 'STON/O2. 3101282' 7.925 nan]
 ...
 [0 3 'Johnston, Miss. Catherine Helen "Carrie"' ... 'W./C. 6607' 23.45
  nan]
 [1 1 'Behr, Mr. Karl Howell' ... '111369' 30.0 'C148']
 [0 3 'Dooley, Mr. Patrick' ... '370376' 7.75 nan]]


In [22]:
print(y)

['S' 'C' 'S' 'S' 'S' 'Q' 'S' 'S' 'S' 'C' 'S' 'S' 'S' 'S' 'S' 'S' 'Q' 'S'
 'S' 'C' 'S' 'S' 'Q' 'S' 'S' 'S' 'C' 'S' 'Q' 'S' 'C' 'C' 'Q' 'S' 'C' 'S'
 'C' 'S' 'S' 'C' 'S' 'S' 'C' 'C' 'Q' 'S' 'Q' 'Q' 'C' 'S' 'S' 'S' 'C' 'S'
 'C' 'S' 'S' 'C' 'S' 'S' 'C' nan 'S' 'S' 'C' 'C' 'S' 'S' 'S' 'S' 'S' 'S'
 'S' 'C' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'Q' 'S' 'S' 'S' 'S' 'S' 'S' 'S'
 'S' 'S' 'S' 'S' 'S' 'S' 'C' 'C' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S'
 'S' 'Q' 'S' 'C' 'S' 'S' 'C' 'S' 'Q' 'S' 'C' 'S' 'S' 'S' 'C' 'S' 'S' 'C'
 'Q' 'S' 'C' 'S' 'C' 'S' 'S' 'S' 'S' 'C' 'S' 'S' 'S' 'C' 'C' 'S' 'S' 'Q'
 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'C' 'Q' 'S' 'S' 'S' 'S' 'S'
 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'Q' 'S' 'S' 'C' 'S' 'S' 'C' 'S' 'S'
 'S' 'C' 'S' 'S' 'S' 'S' 'Q' 'S' 'Q' 'S' 'S' 'S' 'S' 'S' 'C' 'C' 'Q' 'S'
 'Q' 'S' 'S' 'S' 'S' 'C' 'S' 'S' 'S' 'C' 'Q' 'C' 'S' 'S' 'S' 'S' 'Q' 'C'
 'S' 'S' 'C' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S'
 'S' 'S' 'S' 'S' 'S' 'S' 'C' 'Q' 'S' 'S' 'C' 'Q' 'S

In [23]:
#Dropping Columns which are not usefull, so we drop 3 of them here according to our convenience
cols = ['Name', 'Ticket', 'Cabin']
df = df.drop(cols, axis=1)

In [24]:
#Taking a look at the newly formed data format below
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.7+ KB


In [25]:
#Dropping the rows that have missing values
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    712 non-null int64
Survived       712 non-null int64
Pclass         712 non-null int64
Sex            712 non-null object
Age            712 non-null float64
SibSp          712 non-null int64
Parch          712 non-null int64
Fare           712 non-null float64
Embarked       712 non-null object
dtypes: float64(2), int64(5), object(2)
memory usage: 55.6+ KB


In [26]:
#Creating Dummy Variables
dummies = []
cols = ['Pclass', 'Sex', 'Embarked']
for col in cols:
    dummies.append(pd.get_dummies(df[col]))
titanic_dummies = pd.concat(dummies, axis=1)

In [28]:
#Combining the original dataset
df = pd.concat((df,titanic_dummies), axis=1)

In [29]:
df = df.drop(['Pclass', 'Sex', 'Embarked'], axis=1)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 22 columns):
PassengerId    712 non-null int64
Survived       712 non-null int64
Age            712 non-null float64
SibSp          712 non-null int64
Parch          712 non-null int64
Fare           712 non-null float64
1              712 non-null uint8
2              712 non-null uint8
3              712 non-null uint8
female         712 non-null uint8
male           712 non-null uint8
C              712 non-null uint8
Q              712 non-null uint8
S              712 non-null uint8
1              712 non-null uint8
2              712 non-null uint8
3              712 non-null uint8
female         712 non-null uint8
male           712 non-null uint8
C              712 non-null uint8
Q              712 non-null uint8
S              712 non-null uint8
dtypes: float64(2), int64(4), uint8(16)
memory usage: 50.1 KB


In [33]:
#Taking care of the missing data by interpolate function
df['Age'] = df['Age'].interpolate()

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 22 columns):
PassengerId    712 non-null int64
Survived       712 non-null int64
Age            712 non-null float64
SibSp          712 non-null int64
Parch          712 non-null int64
Fare           712 non-null float64
1              712 non-null uint8
2              712 non-null uint8
3              712 non-null uint8
female         712 non-null uint8
male           712 non-null uint8
C              712 non-null uint8
Q              712 non-null uint8
S              712 non-null uint8
1              712 non-null uint8
2              712 non-null uint8
3              712 non-null uint8
female         712 non-null uint8
male           712 non-null uint8
C              712 non-null uint8
Q              712 non-null uint8
S              712 non-null uint8
dtypes: float64(2), int64(4), uint8(16)
memory usage: 50.1 KB


In [35]:
#using the concept of survived vlues, we conver and view the dataframe to NumPy
X = df.values
y = df['Survived'].values

In [36]:
X = np.delete(X, 1, axis=1)

In [37]:
#Dividing data set into training set and test set (Most important step)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [38]:
print(X_train)

[[203.  34.   0. ...   0.   0.   1.]
 [440.  31.   0. ...   0.   0.   1.]
 [103.  21.   0. ...   0.   0.   1.]
 ...
 [792.  16.   0. ...   0.   0.   1.]
 [706.  39.   0. ...   0.   0.   1.]
 [859.  24.   0. ...   1.   0.   0.]]


In [39]:
print(y_train)

[0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0
 1 0 1 0 1 0 0 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 0 1 0 0 0 1 0 0 1 1 0 1 0 1 1
 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0
 1 1 1 0 1 1 0 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 0 1 1 0 0 0 1 0 0 1 0 1 1 0 1
 0 1 1 0 1 0 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1
 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1 1 1 0 0 0 0
 0 0 1 0 0 0 1 0 0 1 0 0 1 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 0 0 1 1 1 0 1 0 1
 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 1 1 0 0
 0 0 1 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 0 0 1 0 1 1 0 0 0 0 1 1 1 0 0 1 1 0
 1 1 1 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 1 1 1 1 0 1 0
 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 1 1 0 1
 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1
 0 1 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0 0 1
 0 0 1 1 0 1 1 0 0 1 1 1 

In [40]:
print(X_test)

[[424.    28.     1.   ...   0.     0.     1.  ]
 [179.    30.     0.   ...   0.     0.     1.  ]
 [306.     0.92   1.   ...   0.     0.     1.  ]
 ...
 [672.    31.     1.   ...   0.     0.     1.  ]
 [581.    25.     1.   ...   0.     0.     1.  ]
 [337.    29.     1.   ...   0.     0.     1.  ]]


In [41]:
print(y_test)

[0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 1 0 1 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 1
 1 1 1 1 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 1 1 1
 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 0 0 1 0 0 0 0
 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 0 1 0 0 1 0 1 1 1 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 1
 1 0 0 0 1 0 0 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 1 0 1 1 0 1 0]


In [51]:
#Using the concept of feature scaling
from sklearn.preprocessing import StandardScaler
sc =  StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])

In [52]:
print(X_train)

[[ 2.03000000e+02  3.40000000e+01  0.00000000e+00 ... -4.88677777e-01
  -1.93649167e-01  5.44862368e-01]
 [ 4.40000000e+02  3.10000000e+01  0.00000000e+00 ... -4.88677777e-01
  -1.93649167e-01  5.44862368e-01]
 [ 1.03000000e+02  2.10000000e+01  0.00000000e+00 ... -4.88677777e-01
  -1.93649167e-01  5.44862368e-01]
 ...
 [ 7.92000000e+02  1.60000000e+01  0.00000000e+00 ... -4.88677777e-01
  -1.93649167e-01  5.44862368e-01]
 [ 7.06000000e+02  3.90000000e+01  0.00000000e+00 ... -4.88677777e-01
  -1.93649167e-01  5.44862368e-01]
 [ 8.59000000e+02  2.40000000e+01  0.00000000e+00 ...  2.04633819e+00
  -1.93649167e-01 -1.83532587e+00]]


In [53]:
print(y_train)

[0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0
 1 0 1 0 1 0 0 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 0 1 0 0 0 1 0 0 1 1 0 1 0 1 1
 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0
 1 1 1 0 1 1 0 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 0 1 1 0 0 0 1 0 0 1 0 1 1 0 1
 0 1 1 0 1 0 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1
 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1 1 1 0 0 0 0
 0 0 1 0 0 0 1 0 0 1 0 0 1 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 0 0 1 1 1 0 1 0 1
 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 1 1 0 0
 0 0 1 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 0 0 1 0 1 1 0 0 0 0 1 1 1 0 0 1 1 0
 1 1 1 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 1 1 1 1 0 1 0
 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 1 1 0 1
 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1
 0 1 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0 0 1
 0 0 1 1 0 1 1 0 0 1 1 1 

In [54]:
print(X_test)

[[ 4.24000000e+02  2.80000000e+01  1.00000000e+00 ... -4.88677777e-01
  -1.93649167e-01  5.44862368e-01]
 [ 1.79000000e+02  3.00000000e+01  0.00000000e+00 ... -4.88677777e-01
  -1.93649167e-01  5.44862368e-01]
 [ 3.06000000e+02  9.20000000e-01  1.00000000e+00 ... -4.88677777e-01
  -1.93649167e-01  5.44862368e-01]
 ...
 [ 6.72000000e+02  3.10000000e+01  1.00000000e+00 ... -4.88677777e-01
  -1.93649167e-01  5.44862368e-01]
 [ 5.81000000e+02  2.50000000e+01  1.00000000e+00 ... -4.88677777e-01
  -1.93649167e-01  5.44862368e-01]
 [ 3.37000000e+02  2.90000000e+01  1.00000000e+00 ... -4.88677777e-01
  -1.93649167e-01  5.44862368e-01]]


In [55]:
print(y_test)

[0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 1 0 1 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 1
 1 1 1 1 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 1 1 1
 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 0 0 1 0 0 0 0
 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 0 1 0 0 1 0 1 1 1 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 1
 1 0 0 0 1 0 0 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 1 0 1 1 0 1 0]


In [56]:
#End of program